### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by safaraliyevelmir** [Tural-91/PragmatechFoundationProject#1]
Salam. SIzdə layihədə elə bir problem görmədim. Başlayın yavaş yavaş layihəni səliqəyə salmağa sonra yenidən feedback verim hələki struktur yaxşıdı bir imgləri folderə atın.

**Comment by Tural-91** [comment]
Salam, bu həftə ərzində bitirərəm. Təşəkkür edirəm

5 iyl 2021, B.e. tarixində 14:35 tarixində safaraliyevelmir <
***@***.***> yazdı:
